version: "3"
name: app
services:
  postgres:
    container_name: postgres
    image: postgres:14.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hello_dev
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.15
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin
  rabbitmq:
    container_name: rabbitmq
    hostname: "rabbit"
    image: rabbitmq:3.9.24-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
  redisinsight:
    container_name: redisinsight
    hostname: redisinsight
    image: redislabs/redisinsight:1.13.1
    ports:
      - 8001:8001
    volumes:
      - /Users/${USERNAME}/redisinsight:/db
  redis:
    container_name: redis-server
    image: redis:7.0.5-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  postgres:
  pgadmin:
  rabbitmq:
  redis:
  redisinsight: