# ./Dockerfile

# Use an official Elixir runtime as a parent image.
FROM elixir:1.14-alpine

# Install required packages
RUN apk update && \
    apk add postgresql-client && \
    apk add git && \
    apk add --no-cache --upgrade bash

# Create app directory and copy the Elixir projects into it.
RUN mkdir /app
COPY . /app
WORKDIR /app

# Install Hex package manager.
RUN mix local.rebar --force && \
    mix local.hex --force

# Compile the project.
RUN mix do deps.get, deps.compile

COPY entrypoint.sh .
CMD ["/bin/bash", "./entrypoint.sh"]